import { createClient } from '@/lib/supabase/server'

export async function POST(request: Request) {
  try {
    const supabase = await createClient()
    
    // Check authentication
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    
    if (authError || !user) {
      return Response.json(
        { error: 'Unauthorized. Please sign in to post comments.' },
        { status: 401 }
      )
    }
    
    // Parse request body
    const body = await request.json()
    const { content, target_type, target_id } = body
    
    // Validate input
    if (!content || !content.trim()) {
      return Response.json(
        { error: 'Comment cannot be empty' },
        { status: 400 }
      )
    }
    
    if (content.length > 200) {
      return Response.json(
        { error: 'Comment must be 200 characters or less' },
        { status: 400 }
      )
    }
    
    if (!target_type || !['profile', 'match', 'season'].includes(target_type)) {
      return Response.json(
        { error: 'Invalid target_type. Must be profile, match, or season' },
        { status: 400 }
      )
    }
    
    if (!target_id) {
      return Response.json(
        { error: 'target_id is required' },
        { status: 400 }
      )
    }
    
    // Step 1: Check users table for auth_id -> discord_user_id mapping
    const { data: userRecord } = await supabase
      .from('users')
      .select('discord_user_id')
      .eq('auth_id', user.id)
      .maybeSingle()
    
    if (!userRecord || !userRecord.discord_user_id) {
      return Response.json(
        { error: 'User not linked to Discord account. Please link your account via the Discord bot.' },
        { status: 404 }
      )
    }
    
    // Step 2: Get player by discord_user_id from users table
    const { data: player, error: playerError } = await supabase
      .from('players')
      .select('id')
      .eq('discord_user_id', userRecord.discord_user_id)
      .maybeSingle()
    
    if (playerError || !player) {
      return Response.json(
        { error: 'Player not found. Please link your Discord account.' },
        { status: 404 }
      )
    }
    
    // Insert comment (censoring is handled by database trigger)
    const { data: comment, error: insertError } = await supabase
      .from('comments')
      .insert({
        author_id: player.id,
        target_type,
        target_id,
        content: content.trim(),
        // content_censored will be auto-generated by trigger
      })
      .select('*, author:players(*)')
      .single()
    
    if (insertError) {
      console.error('Error inserting comment:', insertError)
      return Response.json(
        { error: 'Failed to post comment. Please try again.' },
        { status: 500 }
      )
    }
    
    return Response.json(comment, { status: 201 })
  } catch (error) {
    console.error('Unexpected error in comment API:', error)
    return Response.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
