import { createClient } from '@/lib/supabase/server'
import { getSupabaseAdminClient } from '@/lib/supabase/admin'

export async function POST(request: Request) {
  try {
    const supabase = await createClient()
    
    // Check authentication
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    
    if (authError || !user) {
      return Response.json(
        { error: 'Unauthorized. Please sign in to post comments.' },
        { status: 401 }
      )
    }
    
    // Parse request body
    const body = await request.json()
    const { content, target_type, target_id } = body
    
    // Validate input
    if (!content || !content.trim()) {
      return Response.json(
        { error: 'Comment cannot be empty' },
        { status: 400 }
      )
    }
    
    if (content.length > 200) {
      return Response.json(
        { error: 'Comment must be 200 characters or less' },
        { status: 400 }
      )
    }
    
    if (!target_type || !['profile', 'match', 'season'].includes(target_type)) {
      return Response.json(
        { error: 'Invalid target_type. Must be profile, match, or season' },
        { status: 400 }
      )
    }
    
    if (!target_id) {
      return Response.json(
        { error: 'target_id is required' },
        { status: 400 }
      )
    }
    
    // Use admin client to check users table (bypasses RLS)
    const supabaseAdmin = getSupabaseAdminClient()
    
    // Step 1: Check users table for auth_id -> discord_user_id mapping
    const { data: userRecord } = await supabaseAdmin
      .from('users')
      .select('discord_user_id')
      .eq('auth_id', user.id)
      .maybeSingle() as { data: { discord_user_id: string } | null }
    
    if (!userRecord || !userRecord.discord_user_id) {
      return Response.json(
        { error: 'User not linked to Discord account. Please link your account via the Discord bot.' },
        { status: 404 }
      )
    }
    
    // Step 2: Get player by discord_user_id from users table (use admin client)
    const { data: player, error: playerError } = await supabaseAdmin
      .from('players')
      .select('id')
      .eq('discord_user_id', userRecord.discord_user_id)
      .maybeSingle() as { data: { id: string } | null; error: unknown }
    
    if (playerError || !player || !player.id) {
      return Response.json(
        { error: 'Player not found. Please link your Discord account.' },
        { status: 404 }
      )
    }
    
    // Insert comment (use admin client to bypass RLS)
    const { data: comment, error: insertError } = await (
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      supabaseAdmin.from('comments') as any)
      .insert({
        author_id: player.id,
        target_type,
        target_id,
        content: content.trim(),
        // content_censored will be auto-generated by trigger
      })
      .select('*, author:players(*)')
      .single()
    
    if (insertError || !comment) {
      console.error('Error inserting comment:', insertError)
      return Response.json(
        { error: 'Failed to post comment. Please try again.' },
        { status: 500 }
      )
    }
    
    return Response.json(comment, { status: 201 })
  } catch (error) {
    console.error('Unexpected error in comment API:', error)
    return Response.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
